services:
  app:
    image: blog-posts:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - 8011:80
  db:
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: blog-posts
        MYSQL_USER: blog-posts
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - ./dbdata:/var/lib/mysql
    ports: 
        - "8012:3306"